//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entityframework_database_mvc_crud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db90_18124Entities : DbContext
    {
        public db90_18124Entities()
            : base("name=db90_18124Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
    
        public virtual int employee_delete(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_delete", empidParameter);
        }
    
        public virtual ObjectResult<employee_edit_Result> employee_edit(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<employee_edit_Result>("employee_edit", empidParameter);
        }
    
        public virtual ObjectResult<employee_get_Result> employee_get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<employee_get_Result>("employee_get");
        }
    
        public virtual int employee_insert(string name, string city, Nullable<long> mobile, Nullable<int> age)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(long));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_insert", nameParameter, cityParameter, mobileParameter, ageParameter);
        }
    
        public virtual int employee_update(Nullable<int> empid, string name, string city, Nullable<long> mobile, Nullable<int> age)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(long));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_update", empidParameter, nameParameter, cityParameter, mobileParameter, ageParameter);
        }
    }
}
